import Head from "next/head";
// import Image from "next/image";
// import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Card from "@/componentes/card";
import { useEffect, useState } from "react";
import Clock from "@/componentes/Clock";
import Cronometro from "@/componentes/cronometro";
import ButtonPlus from "@/componentes/buttons/button_plus";

// const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  /* esto es una promesa para obtener datos desde un backend */

  const [info, setInfo] = useState();
  useEffect(() => {
    const randomCharacter = Math.ceil(Math.random() * 826);
    fetch("https://rickandmortyapi.com/api/character/" + randomCharacter)
      .then((response) => response.json())
      .then((data) => setInfo([data]));
  }, []);
  if (info === undefined) {
    return <div>Loading...</div>;
  }
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Clock> </Clock>
        Hola Mundo
        <Cronometro></Cronometro>
        <ButtonPlus></ButtonPlus>
        {info.map((element) => (
          <Card
            key={element.name}
            name={element.name}
            img={element.image}
          ></Card>
        ))}
      </main>
    </>
  );
}

// setInterval( sadfsfsdf ,1000) //Cada x segundos llama a esa funcion
