import Head from "next/head";
import styles from "@/styles/Home.module.css";
import Cronometro from "@/componentes/Reloj-Cronometro/cronometro";
import ButtonPlus from "@/componentes/buttons/button_plus";
import Navbar from "@/componentes/navbar/navbar";
import Darkmode from "@/componentes/buttons/darkmode";

export default function Test() {
  return (
    <>
      <Head>
        <title>Testing Page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Navbar></Navbar>
        Cronometro
        <Cronometro></Cronometro>
        Subir y bajar
        <ButtonPlus></ButtonPlus>
        <Darkmode></Darkmode>
      </main>
    </>
  );
}
